name: todos
description: A Streamed version of the Riverpod 'todos' example, merged with
  Bloc 'todos' example.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ">=0.16.0-nullsafety.0 <2.0.0"
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  rive_bloc: ^0.0.1
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
  uuid: ^4.2.0

dev_dependencies:
  build_runner: ^2.0.0
  custom_lint: ^0.6.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
